### ISSUE TITLE
Examples are not worked

### ISSUE THREAD

**Issue by zxweed** [sevamoo/SOMPY#39]
Can you make any of the examples worked please? None of it can be runned because of changes in the sompy library (parameters/methods names, etc)

In the sample
http://nbviewer.jupyter.org/urls/gist.githubusercontent.com/sevamoo/8f26d64470e00960684a/raw/SOMPY_example

the constructor call has the wrong parameters:

`sm = SOM.SOM('sm', Data, mapsize = [msz0, msz1],norm_method = 'var',initmethod='pca')`

and so on..

**Comment by sevamoo** [comment]
I believe this example works: http://nbviewer.jupyter.org/gist/sevamoo/ec0eb28229304f4575085397138ba5b1
As it is mentioned in the readme, the others need to be adjusted. 
Since it is an open source project, please, update those other examples based on the working one and send me a pull request. 
Best
Vahid

**Comment by sevamoo** [comment]
@zxweed please, let me know if you could run the example
Best
Vahid

**Comment by zxweed** [comment]
Thanks, I can run this example with two corrections:

> import **SOMPY** as sompy
> import sys
> import **SOMPY** as sompy

SOMPY must be in lower case and only one line.

> v.show(som, what='codebook', which_dim=[0,1], **CMAP=None,** col_sz=6) #which_dim='all' default

CMAP parameter is absent, so I remove it

If I able to fix the other examples - I will make a pull request.

**Comment by sevamoo** [comment]
Thanks. Just updated the example. 
Would be great if you managed to work on other examples.
Best
