### ISSUE TITLE
Please take down the notebooks or update

### ISSUE THREAD

**Issue by Aakash282** [sevamoo/SOMPY#55]
took me over 30 mins to figure out how to run a basic example.

**Comment by sevamoo** [comment]
I believe this example should work?! 
https://gist.github.com/sevamoo/035c56e7428318dd3065013625f12a11
@Aakash282  Now then, can you send me a running basic example beside this one? I'll immediately, update it.

**Comment by Aakash282** [comment]
This issue was created in relation to [Notebook 1](http://nbviewer.jupyter.org/gist/sevamoo/e93699fdb481de1a932b) listed in the README. Got confused by this example code and then had to piece together my own example. 

Here is a stripped down version of my code: 
https://gist.github.com/Aakash282/ca4c1a37748e4b891b5e4282a7cf5ab1

Thanks

**Comment by sevamoo** [comment]
Thanks. But you see as it is written one line above it " The following examples, need some modifications, since the library has been modified. However, it should be easy to figure out how to use them." 
Sorry for confusion anyways. 
So, now considering the example I sent you, should we update the README and your new examples?
Thanks

**Comment by Aakash282** [comment]
Definitely update the notebooks!

**Comment by sevamoo** [comment]
I realized that those notebooks were not so informative. So, for now I just modified the README file with no misleading examples and only one basic usage. Feel free to update it by new examples. (preferably notebook format).
